sudo: true
dist: xenial
language: node_js
jobs:
  include:
    - stage: build docker image
      if: tag IS present
      before_install:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo `git tag -l --points-at HEAD | tail -1`
      install:
      - docker build -t "$DOCKER_USERNAME/core:latest" .
      script:
      - docker push "$DOCKER_USERNAME/core:latest"

