sudo: true
dist: xenial
language: node_js
jobs:
  include:
    - stage: build docker image, test and push it
      if: tag IS present
      install: true
      script:
      - docker build -t "$DOCKER_USERNAME/core:$TRAVIS_TAG" .
      - docker run --entrypoint '' "$DOCKER_USERNAME/core:$TRAVIS_TAG" npm test
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$DOCKER_USERNAME/core:$TRAVIS_TAG" .
